version: "3.9"

services:
  devretrogames_300725183240_tutorias_python_devcontainer:
    container_name: devretrogames_300725183240_tutorias_python_devcontainer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/Tutorias_Python:cached
    command: sleep infinity
    networks:
      net_interna:
        aliases:
          - Tutorias_Python_devcontainer

networks:
  net_interna:
    name: Tutorias_Python
    driver: bridge
    ipam:
      driver: default