version: "3.9"

services:
  DevRetroGames_300725183240_Tutorias_Python_devcontainer:
    image: mcr.microsoft.com/devcontainers/base:noble
    container_name: DevRetroGames_300725183240_Tutorias_Python_devcontainer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/Tutorias_Python:cached
    command: sleep infinity
    networks:
      net_interna:
        aliases:
          - Tutorias_Python_devcontainer

networks:
  net_interna:
    name: Tutorias_Python
    driver: bridge
    ipam:
      driver: default